### ISSUE TITLE
Add /recent endpoint

### ISSUE THREAD

**Issue by zozs** [zozs/i#2]
It would be nice with a `/recent` endpoint which lists the most recent uploads made to the uploading service.

This simplifies things if you accidentally discard the link to the random filename, or want to send an old link again to somewhere else.

The endpoint should have the same access control as the upload endpoint, so that not anyone can just list recent uploads.

Primarily, I think the endpoint should list the recent uploads in HTML format, so you can view it in your browser. In addition, it _could_ also return JSON, if it would be seen as useful for some reason. In theory, both could use the same endpoint, just differentiated by the value of the `Accept` header.

**Comment by danielhamngren** [comment]
I'm dipping my toes in Rust programming and cblgh directed me to this "good first issue". This issue seem like it is just outside my comfort zone. Perfect! 

I have some thoughts on how I want to do the implementation. Hopefully I have some code to contribute by the end of the weekend.

**Comment by zozs** [comment]
Closing since it was merged some time ago, thanks again! :tada:
